#!/usr/bin/env python

def get_options():
    import argparse

    description = 'Score aminoacid changes using their categories'
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('nonsyn',
                        help='Nonsynonymous file (format: A1Z PROT1)')
    
    return parser.parse_args()

if __name__ == "__main__":
    options = get_options()

    aa = {'hydrophobic': {'A', 'I', 'L', 'M', 'V'},
          'hydrophobic-aromatic': {'F', 'W', 'Y'},
          'polar': {'N', 'Q', 'S', 'T'},
          'acidic': {'D', 'E'},
          'basic': {'R', 'H', 'K'},
          'cysteine': {'C'},
          'proline': {'P'},
          'glycine': {'G'}}
    r = {}
    for k, v in aa.items():
        for a in v:
            r[a] = k

    for l in open(options.nonsyn):
        mut, prot = l.rstrip().split()
        a1, a2 = mut[0], mut[-1]
        if r[a1] != r[a2]:
            print('%s\t%s\t0.01' % (prot, mut))
        else:
            print('%s\t%s\t0.99' % (prot, mut))
