#!/usr/bin/env python
'''Amend pangenome to reflect the parental strain background'''

def parse_orthologs(f):
    d = {}
    for l in open(f):
        if l.startswith('#'):
            continue
        o, p, i = l.rstrip().split('\t')
        d[o] = d.get(o, set())
        d[o].add( (p, i) )
    return d

if __name__ == "__main__":
    import sys
    
    d = parse_orthologs(sys.argv[1])
    g = {x.rstrip() for x in open(sys.argv[2])}
    for k in d:
        if 'target' not in {x[1] for x in d[k]}:
            for prot in {x[0] for x in d[k]}:
                if prot in g:
                    d[k].add(('x', 'target'))
                    break
    
    print('#orth_id\tprot_id\torg_id')
    for k in d:
        for p, o in d[k]:
            print('%s\t%s\t%s' % (k, p, o))
