#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'


def get_options():
    import argparse

    # create the top-level parser
    description = "Convert BED format to SIFT table"
    parser = argparse.ArgumentParser(description=description,
                                     prog='bed2sift')

    parser.add_argument('--version', action='version',
                        version='%(prog)s '+__version__)

    return parser.parse_args()

if __name__ == "__main__":
    options = get_options()

    import sys

    for l in sys.stdin:
        uniprot, start, end, mut, score = l.rstrip().split('\t')
        pos = int(start)
        aa1 = mut[0]
        aa2 = mut[-1]
        print('\t'.join((uniprot,
                         '%s%d%s' % (aa1, pos, aa2),
                         score)))
