#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'


def get_options():
    import argparse

    # create the top-level parser
    description = "Collect bootstraps"
    parser = argparse.ArgumentParser(description=description,
                                     prog='collect_overall_bootstraps')

    parser.add_argument('folder', action='store',
                        help='bootstraps folder')

    parser.add_argument('--version', action='version',
                        version='%(prog)s '+__version__)

    return parser.parse_args()

def mad(data, axis=None):
    return np.median(np.absolute(data - np.median(data, axis)), axis)

if __name__ == "__main__":
    import os
    import sys
    import pandas as pd
    import numpy as np

    options = get_options()
    
    roc = []
    prec = []
    mcc = []
    boots = os.listdir(options.folder)
    px = np.linspace(0, 1, 15)
    for b in boots:
        m = pd.read_table(os.path.join(options.folder, b),
                          header=None)
        m.columns = ['iter',
                     'stat', 'threshold',
                     'x', 'y', 'kind']
        for i in set(m['iter']):
            k = m[m['iter'] == i]
            py = np.interp(px,
                           k[k['kind'] == 'roc']['x'],
                           k[k['kind'] == 'roc']['y'])
            pt = np.interp(px,
                           k[k['kind'] == 'roc']['x'],
                           k[k['kind'] == 'roc']['threshold'])
            roc.append((py, pt))
            py = np.interp(px,
                           k[k['kind'] == 'prec']['x'],
                           k[k['kind'] == 'prec']['y'])
            pt = np.interp(px,
                           k[k['kind'] == 'roc']['x'],
                           k[k['kind'] == 'roc']['threshold'])
            prec.append((py, pt))
            py = np.interp(px,
                           k[k['kind'] == 'mcc']['x'],
                           k[k['kind'] == 'mcc']['y'])
            pt = np.interp(px,
                           k[k['kind'] == 'roc']['x'],
                           k[k['kind'] == 'roc']['threshold'])
            mcc.append((py, pt))

    r = np.array(roc)
    for x, y, m, t in zip(px,
            np.median(r[:, 0], axis=0),
            mad(r[:, 0], axis=0),
            np.median(r[:, 1], axis=0)):
        print('\t'.join(('roc', str(x), str(y), str(m), str(t))))
    r = np.array(prec)
    for x, y, m, t in zip(px,
            np.median(r[:, 0], axis=0),
            mad(r[:, 0], axis=0),
            np.median(r[:, 1], axis=0)):
        print('\t'.join(('prec', str(x), str(y), str(m), str(t))))
    r = np.array(mcc)
    for x, y, m, t in zip(px,
            np.median(r[:, 0], axis=0),
            mad(r[:, 0], axis=0),
            np.median(r[:, 1], axis=0)):
        print('\t'.join(('mcc', str(x), str(y), str(m), str(t))))
