#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'


def get_options():
    import argparse

    # create the top-level parser
    description = "Collect bootstraps"
    parser = argparse.ArgumentParser(description=description,
                                     prog='collect_overall_bootstraps')

    parser.add_argument('folder', action='store',
                        help='bootstraps folder')

    parser.add_argument('--version', action='version',
                        version='%(prog)s '+__version__)

    return parser.parse_args()

if __name__ == "__main__":
    import os
    import pandas as pd
    import numpy as np

    options = get_options()

    folders = os.listdir(options.folder)
    for d in folders:
        boots = os.listdir(os.path.join(options.folder, d))
        res = []
        for b in boots:
            bootstrap = pd.read_table(os.path.join(options.folder, d, b),
                                      header=None)
            bootstrap.columns = ['auc', 'tpr', 'fpr']
            auc = bootstrap.auc.values[0]
            print(auc)
