#!/usr/bin/env python
'''
From a list of essential genes get
their Uniprot identifiers
'''

__author__ = "Marco Galardini"
__version__ = '0.1.0'


def get_options():
    import argparse

    # create the top-level parser
    description = "Get all the Uniprot IDs from an essential genes list"
    parser = argparse.ArgumentParser(description=description,
                                     prog='essential2uniprot')
    parser.add_argument('essential', action='store',
                        help='essential genes file')
    parser.add_argument('conversion', action='store',
                        help='locus to uniprot file')

    parser.add_argument('--version', action='version',
                        version='%(prog)s '+__version__)

    return parser.parse_args()

if __name__ == "__main__":
    options = get_options()

    # avoid essential genes
    essential = {x.rstrip()
                 for x in open(options.essential)}
    l2u = {x.rstrip().split()[0]: x.rstrip().split()[1]
           for x in open(options.conversion)}
    essential = {l2u.get(x, x) for x in essential}
    for gene in sorted(essential):
        print(gene)
