#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'


def get_options():
    import argparse

    # create the top-level parser
    description = "Remove duplicates from Roary"
    parser = argparse.ArgumentParser(description=description,
                                     prog='fix_roary')

    parser.add_argument('roary', action='store',
                        help='Roary output file')

    parser.add_argument('--version', action='version',
                        version='%(prog)s '+__version__)

    return parser.parse_args()


if __name__ == "__main__":
    import sys
    import pandas as pd

    options = get_options()

    roary = pd.read_table(options.roary,
                          sep=',',
                          low_memory=False)
    columns = sorted(roary.columns[14:])
    strains = {x.split('_')[0]
               for x in columns}
    d = {}
    remove = set()
    for s in strains:
        ss = [x for x in columns
              if x.split('_')[0] == s]
        s1 = ss[0]
        if len(ss) > 1:
            for x in ss[1:]:
                remove.add(x)
        d[s1] = s
    d['genome'] = 'NT12001'

    roary.drop(remove, axis=1, inplace=True)
    roary.rename(columns=d, inplace=True)

    roary.to_csv(sys.stdout, index=None)
