#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'


def get_options():
    import argparse

    # create the top-level parser
    description = "Get the AUC for the predictions"
    parser = argparse.ArgumentParser(description=description,
                                     prog='score_auc')

    parser.add_argument('predictions', action='store',
                        help='Predictions file')
    parser.add_argument('matrix', action='store',
                        help='EMAP matrix')
    parser.add_argument('fdr', action='store',
                        help='FDR matrix')

    parser.add_argument('--fdr-threshold', action='store',
                        type=float,
                        default=0.05,
                        help='FDR threshold [Default: 0.05]')
    parser.add_argument('--comparison-matrix', action='store',
                        default=None,
                        help='MCC comparison matrix [Default: the same one]')

    parser.add_argument('--version', action='version',
                        version='%(prog)s '+__version__)

    return parser.parse_args()

def transform_matrices(a, z, m):
    y_pred = m[np.invert(np.isnan(a))]
    y_true = z.loc[m.index, m.columns].copy(deep=True)
    y_true[np.invert(np.isnan(a))] = 0
    y_true[np.invert(np.isnan(z))] = 1
    y_true[np.isnan(a)] = np.nan
    y_true[np.isnan(m)] = np.nan
    
    return y_true, y_pred

def get_data(a, z, m):
    y_true, y_pred = transform_matrices(a, z, m)
    
    y = pd.DataFrame([y_true.values.flatten(),
                      y_pred.values.flatten()]).T.dropna()
    return y[0], y[1]

def evaluate(y_true, y_pred):
    prec, rec, pthresholds = precision_recall_curve(y_true, y_pred)
    prec_auc = auc(rec, prec)

    fpr, tpr, rthresholds = roc_curve(y_true, y_pred)
    roc_auc = auc(fpr, tpr)

    tv = y_true.copy(deep=True)
    tv[tv == 0] = -1
    tv[tv == 1] = 1
    x_mcc = []
    y_mcc = []
    f1s = []
    for t in np.arange(0, 1, 0.005):
        s1 = np.array(y_pred)
        s1[s1 >= t] = 1
        s1[s1 < t] = -1
        x_mcc.append(t)
        y_mcc.append(matthews_corrcoef(tv, s1))
        s2 = np.array(y_pred)
        s2[s2 >= t] = 1
        s2[s2 < t] = 0
        f1s.append(f1_score(y_true, s2))
    
    return (rec, prec, prec_auc, pthresholds), (fpr, tpr, roc_auc, rthresholds), (x_mcc, y_mcc, f1s)

if __name__ == "__main__":
    import pandas as pd
    import numpy as np
    from sklearn.metrics import roc_curve, auc, precision_recall_curve
    from sklearn.metrics import f1_score, matthews_corrcoef
    from sklearn import preprocessing

    options = get_options()

    # Read strains data
    a = pd.read_table(options.matrix)
    a.set_index(a.columns[0], inplace=True)
    # Load the FDR corrections to identify proper phenotypes
    f = pd.read_table(options.fdr)
    f.set_index(f.columns[0], inplace=True)

    # Apply the FDR correction
    v = a[f < options.fdr_threshold]
    v = v[v < 0]

    m = pd.read_table(options.predictions)
    m.set_index(m.columns[0], inplace=True)
    m.index.name = 'condition'
    m = m.T

    minmax = preprocessing.MinMaxScaler()

    if options.comparison_matrix is not None:
        m1 = pd.read_table(options.comparison_matrix)
        m1.set_index(m1.columns[0], inplace=True)
        m1.index.name = 'condition'
        m1 = m1.T
        y_true, y_pred = get_data(a, v, m1)
        y_pred = minmax.fit_transform(y_pred.reshape(-1, 1))
    y_true, y_pred = get_data(a, v, m)
    if options.comparison_matrix is not None:
        y_pred = minmax.transform(y_pred.reshape(-1, 1)).reshape(-1, 1)
    else:
        y_pred = minmax.fit_transform(y_pred.reshape(-1, 1)).reshape(-1, 1)
    (rec, prec, prec_auc, pt), (fpr, tpr, roc_auc, rt), (x_mcc, y_mcc, f1s) = evaluate(y_true, y_pred)

    for x, y, z in zip(fpr, tpr, rt):
        print('%.5f\t%.5f\t%.5f\t%.5f\troc' % (roc_auc, z, x, y))
    for x, y, z in zip(x_mcc, y_mcc, f1s):
        print('%.5f\t%.5f\t%.5f\t%.5f\tmcc' % (z, x, x, y))
    for x, y, z in zip(rec, prec, pt):
        print('%.5f\t%.5f\t%.5f\t%.5f\tprec' % (prec_auc, z, x, y))

