#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'


def get_options():
    import argparse

    # create the top-level parser
    description = "Create figure 4"
    parser = argparse.ArgumentParser(description=description,
                                     prog='run_figure_4')
    parser.add_argument('scheme', action='store',
                        help='scheme')
    parser.add_argument('conditions')
    parser.add_argument('associations')
    parser.add_argument('example1')
    parser.add_argument('example2')
    parser.add_argument('example')
    parser.add_argument('outfile',
                        help='output (including extension)')

    parser.add_argument('--version', action='version',
                        version='%(prog)s '+__version__)

    return parser.parse_args()




if __name__ == "__main__":
    options = get_options()
    import svgutils.transform as sg

    #create new SVG figure
    fig = sg.SVGFigure("11in", "11in")

    # load matpotlib-generated figures
    fig1 = sg.fromfile(options.scheme)
    fig3 = sg.fromfile(options.conditions)
    fig5 = sg.fromfile(options.associations)
    fig6 = sg.fromfile(options.example1)
    fig7 = sg.fromfile(options.example2)
    fig10 = sg.fromfile(options.example)

    # get the plot objects
    plot1 = fig1.getroot()
    plot1.moveto(45, 25, scale=2.2)
    plot3 = fig3.getroot()
    plot3.moveto(75, 275, scale=1)
    plot5 = fig5.getroot()
    plot5.moveto(435, 315, scale=1)

    plot6 = fig6.getroot()
    plot6.moveto(430, 545, scale=1)
    plot7 = fig7.getroot()
    plot7.moveto(-10, 545, scale=1)

    plot10 = fig10.getroot()
    plot10.moveto(690, 260, scale=1)

    # add text labels
    txt1 = sg.TextElement(25,  25, "A)", size=12, weight="bold")
    txt2 = sg.TextElement(30, 270, "B)", size=12, weight="bold")
    txt3 = sg.TextElement(425, 270, "C)", size=12, weight="bold")
    txt4 = sg.TextElement(670, 270, "D)", size=12, weight="bold")
    txt5 = sg.TextElement(75, 545, "E)", size=12, weight="bold")

    # append plots and labels to figure
    fig.append([plot3,
                plot5,
                plot1,
                plot6,
                plot7,
                plot10,
               ])
    fig.append([txt1,
                txt2,
                txt3,
                txt4,
                txt5,
               ])

    fig.save(options.outfile)
