#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'


def get_options():
    import argparse

    # create the top-level parser
    description = "Create figure 4"
    parser = argparse.ArgumentParser(description=description,
                                     prog='run_figure_4')
    parser.add_argument('scheme', action='store',
                        help='scheme')
    parser.add_argument('conditions')
    parser.add_argument('associations')
    parser.add_argument('outfile',
                        help='output (including extension)')

    parser.add_argument('--version', action='version',
                        version='%(prog)s '+__version__)

    return parser.parse_args()




if __name__ == "__main__":
    options = get_options()
    import svgutils.transform as sg

    #create new SVG figure
    fig = sg.SVGFigure("7.7in", "6in")

    # load matpotlib-generated figures
    fig1 = sg.fromfile(options.scheme)
    fig3 = sg.fromfile(options.conditions)
    fig5 = sg.fromfile(options.associations)

    # get the plot objects
    plot1 = fig1.getroot()
    plot1.moveto(25, 0, scale=1.95)
    plot3 = fig3.getroot()
    plot3.moveto(75, 275, scale=1)
    plot5 = fig5.getroot()
    plot5.moveto(435, 315, scale=1)

    # add text labels
    txt1 = sg.TextElement(25,  25, "A)", size=12, weight="bold")
    txt2 = sg.TextElement(30, 270, "B)", size=12, weight="bold")
    txt3 = sg.TextElement(425, 270, "C)", size=12, weight="bold")

    # append plots and labels to figure
    fig.append([plot3,
                plot5,
                plot1,
               ])
    fig.append([txt1,
                txt2,
                txt3,
               ])

    fig.save(options.outfile)
