#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'


def get_options():
    import argparse

    # create the top-level parser
    description = "Create figure 1"
    parser = argparse.ArgumentParser(description=description,
                                     prog='run_figure_1')
    parser.add_argument('tree', action='store',
                        help='tree plot')
    parser.add_argument('treebar', action='store',
                        help='treebar plot')
    parser.add_argument('treelegend', action='store',
                        help='treelegend plot')
    parser.add_argument('constraints', action='store',
                        help='constraints plot')
    parser.add_argument('outfile', action='store',
                        help='output (including extension)')

    parser.add_argument('--version', action='version',
                        version='%(prog)s '+__version__)

    return parser.parse_args()

if __name__ == "__main__":
    options = get_options()
    import svgutils.transform as sg

    fig = sg.SVGFigure("10.5in", "6in")

    fig1 = sg.fromfile(options.tree)
    fig2 = sg.fromfile(options.constraints)
    fig3 = sg.fromfile(options.treebar)
    fig4 = sg.fromfile(options.treelegend)

    plot1 = fig1.getroot()
    plot1.moveto(25, 25, scale=0.77)
    plot2 = fig2.getroot()
    plot2.moveto(475, 0, scale=1)
    plot3 = fig3.getroot()
    plot3.moveto(110, 500, scale=1)
    plot4 = fig4.getroot()
    plot4.moveto(0, 495, scale=1)

    txt1 = sg.TextElement(25,  25, "A)", size=12, weight="bold")
    txt2 = sg.TextElement(490, 25, "B)", size=12, weight="bold")
    txt3 = sg.TextElement(620, 25, "C)", size=12, weight="bold")
    txt4 = sg.TextElement(490, 275, "D)", size=12, weight="bold")
    txt5 = sg.TextElement(720, 275, "E)", size=12, weight="bold")

    fig.append([plot1, plot2, plot3, plot4])
    fig.append([txt1, txt2, txt3, txt4, txt5])

    fig.save(options.outfile)
