#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'


def get_options():
    import argparse

    # create the top-level parser
    description = "Run phenotypes plots"
    parser = argparse.ArgumentParser(description=description,
                                     prog='run_categories_roc')

    parser.add_argument('auc')
    parser.add_argument('details')
    parser.add_argument('outfile')

    parser.add_argument('--height', action='store',
                        type=float,
                        default=1,
                        help='Figure height [Default: 1 inches]')
    parser.add_argument('--width', action='store',
                        type=float,
                        default=1,
                        help='Figure width [Default: 1 inches]')
    parser.add_argument('--dpi', action='store',
                        type=int,
                        default=300,
                        help='DPI [Default: 300]')
    
    parser.add_argument('--version', action='version',
                        version='%(prog)s '+__version__)

    return parser.parse_args()


if __name__ == "__main__":
    import pandas as pd

    options = get_options()

    import matplotlib.pyplot as plt
    import seaborn as sns
    import matplotlib as mpl
    import matplotlib.cm as cm
    import matplotlib.patches as patches

    sns.set_style('white')

    plt.rc('font', family='sans-serif') 
    plt.rc('font', serif='Arial') 
    plt.rc('text', usetex='false')
    
    plt.rc('font', size=8)
    plt.rc('xtick', labelsize=8)
    plt.rc('ytick', labelsize=8)
    plt.rc('axes', labelsize=10, titlesize=10)
    plt.rc('legend', fontsize=8)

    plt.figure(figsize=(options.width, options.height))

    conditions = {}
    rconditions = {}
    categories = pd.read_table(
        options.details
        ).set_index('Label')['Type of stress'].to_dict()
    for cat in set(categories.values()):
        conditions[cat] = set()
        for k, v in categories.items():
            if v == cat:
                conditions[cat].add(k)
                rconditions[k] = cat

    chem1 = pd.read_table(
        options.details
        ).set_index('Label')['Chemical 1'].to_dict()
    chem2 = pd.read_table(
        options.details 
        ).set_index('Label')['Chemical 2'].to_dict()

    res = []
    auc = pd.read_table(options.auc,
                        header=None)
    auc.columns = ['condition', 'sick', 'strains', 'stat', 'threshold', 'x', 'y', 'kind']
    auc = auc[auc.kind == 'prec'].groupby('condition').max()['stat'].dropna()
    for c in set(auc.index):
        res.append((c, rconditions[c], auc.loc[c]))
    r = pd.DataFrame(res)
    r.columns = ['condition', 'category', 'auc']

    sns.boxplot(data=r,
                x='auc',
                y='category',
                order=sorted(set(r.category),
                             key=lambda x: r[r.category == x].auc.median()),
                color=sns.xkcd_rgb['pale grey'])
    sns.swarmplot(data=r,
                x='auc',
                y='category',
                order=sorted(set(r.category),
                             key=lambda x: r[r.category == x].auc.median()),
                color=sns.xkcd_rgb['dark grey'],
                alpha=0.5)
    plt.legend([])
    plt.ylabel('Condition category')
    plt.xlabel('PR-AUC')
    plt.xlim(-0.01)
    sns.despine(left=True);

    plt.savefig(options.outfile,
                dpi=options.dpi)
