#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'


def get_options():
    import argparse

    # create the top-level parser
    description = "Create figure 2"
    parser = argparse.ArgumentParser(description=description,
                                     prog='run_figure_2')
    parser.add_argument('scheme', action='store',
                        help='scheme')
    parser.add_argument('replicates', action='store')
    parser.add_argument('correlation1', action='store')
    parser.add_argument('correlation2', action='store')
    parser.add_argument('correlation3', action='store')
    parser.add_argument('tree', action='store')
    parser.add_argument('treelegend', action='store')
    parser.add_argument('treecolorbar', action='store')
    parser.add_argument('purity', action='store')
    parser.add_argument('chemical', action='store')
    parser.add_argument('target', action='store')
    parser.add_argument('outfile', action='store',
                        help='output (including extension)')

    parser.add_argument('--version', action='version',
                        version='%(prog)s '+__version__)

    return parser.parse_args()

if __name__ == "__main__":
    options = get_options()
    import svgutils.transform as sg

    fig = sg.SVGFigure("10.75in", "11in")

    fig1 = sg.fromfile(options.scheme)
    fig2 = sg.fromfile(options.replicates)
    fig3 = sg.fromfile(options.correlation1)
    fig4 = sg.fromfile(options.correlation2)
    fig5 = sg.fromfile(options.correlation3)
    fig6 = sg.fromfile(options.tree)
    fig7 = sg.fromfile(options.treelegend)
    fig8 = sg.fromfile(options.treecolorbar)
    fig9 = sg.fromfile(options.purity)
    fig10 = sg.fromfile(options.chemical)
    fig11 = sg.fromfile(options.target)

    plot1 = fig1.getroot()
    plot1.moveto(25, 25, scale=0.39)
    plot2 = fig2.getroot()
    plot2.moveto(25, 230, scale=1)
    plot3 = fig3.getroot()
    plot3.moveto(25, 450, scale=1)
    plot4 = fig4.getroot()
    plot4.moveto(150, 960, scale=1)
    plot5 = fig5.getroot()
    plot5.moveto(140, 920, scale=1)
    plot6 = fig6.getroot()
    plot6.moveto(575, 25, scale=0.55)
    plot7 = fig7.getroot()
    plot7.moveto(800, 320, scale=1)
    plot8 = fig8.getroot()
    plot8.moveto(535, 370, scale=1)
    plot9 = fig9.getroot()
    plot9.moveto(570, 430, scale=1)
    plot10 = fig10.getroot()
    plot10.moveto(570, 590, scale=1)
    plot11 = fig11.getroot()
    plot11.moveto(570, 725, scale=1)

    txt1 = sg.TextElement(25,  25, "A)", size=12, weight="bold")
    txt2 = sg.TextElement(560, 25, "B)", size=12, weight="bold")
    txt3 = sg.TextElement(25, 250, "C)", size=12, weight="bold")
    txt4 = sg.TextElement(25, 470, "D)", size=12, weight="bold")
    txt5 = sg.TextElement(560, 430, "E)", size=12, weight="bold")
    txt6 = sg.TextElement(560, 590, "F)", size=12, weight="bold")
    txt7 = sg.TextElement(560, 735, "G)", size=12, weight="bold")

    fig.append([plot3,
                plot2,
                plot1,
                plot4,
                plot5,
                plot6,
                plot7,
                plot8,
                plot9,
                plot11,
                plot10,
               ])
    fig.append([txt1,
                txt2,
                txt3,
                txt4,
                txt5,
                txt6,
                txt7,
               ])

    fig.save(options.outfile)
