#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'


def get_options():
    import argparse

    # create the top-level parser
    description = "Run constraint plot"
    parser = argparse.ArgumentParser(description=description,
                                     prog='run_constraints_plot')
    parser.add_argument('features', action='store',
                        help='features file')
    parser.add_argument('siftfeatures', action='store',
                        help='Sift features file')
    parser.add_argument('accessibility', action='store',
                        help='Accessibility file')
    parser.add_argument('foldxaccessibility', action='store',
                        help='Foldx accessibility file')
    parser.add_argument('outfile', action='store',
                        help='Foldx accessibility file')

    parser.add_argument('--sift-offset', action='store',
                        type=float,
                        default=1.527487632E-04,
                        help='SIFT score offset [Default: 1.527487632E-04]')
    
    parser.add_argument('--width', action='store',
                        type=int,
                        default=5,
                        help='Figure width [Default: 5 inches]')
    parser.add_argument('--height', action='store',
                        type=int,
                        default=5,
                        help='Figure height [Default: 5 inches]')
    parser.add_argument('--dpi', action='store',
                        type=int,
                        default=300,
                        help='DPI [Default: 300]')
    
    parser.add_argument('--version', action='version',
                        version='%(prog)s '+__version__)

    return parser.parse_args()

if __name__ == "__main__":
    import numpy as np
    import pandas as pd

    options = get_options()

    import matplotlib.pyplot as plt
    import seaborn as sns

    sns.set_style('white')

    plt.rc('font', family='sans-serif') 
    plt.rc('font', serif='Arial') 
    plt.rc('text', usetex='false')
    
    plt.rc('font', size=8)
    plt.rc('xtick', labelsize=8)
    plt.rc('ytick', labelsize=8)
    plt.rc('axes', labelsize=10, titlesize=18)
    plt.rc('legend', fontsize=8)

    m1 = pd.read_table(options.features, header=None)
    m1.columns = ['set', 'round', 'variability']

    m2 = pd.read_table(options.siftfeatures, header=None)
    m2.columns = ['set', 'round', 'score']
    s = []
    for x in m2['set']:
        if x == 'all features':
            s.append('features')
        elif x == 'all others':
            s.append('others')
        else:
            s.append(x)
    m2['set'] = s
    r = []
    for x in m2['round']:
        if np.isnan(x):
            r.append('Observed')
        elif x == 1:
            r.append('Expected')
        else:
            r.append(np.nan)
    m2['round'] = r
    m2 = m2.dropna()

    m3 = pd.read_table(options.accessibility, header=None)
    m3.columns = ['round', 'start', 'stop', 'variability']

    m4 = pd.read_table(options.foldxaccessibility, header=None)
    m4.columns = ['set', 'round', 'score']
    s = []
    for x in m4['set']:
        if x == 'all buried':
            s.append('buried')
        elif x == 'all others':
            s.append('others')
        else:
            s.append(x)
    m4['set'] = s
    r = []
    for x in m4['round']:
        if np.isnan(x):
            r.append('Observed')
        elif x == 1:
            r.append('Expected')
        else:
            r.append(np.nan)
    m4['round'] = r
    m4 = m4.dropna()

    plt.figure(figsize=(options.width, options.height))

    ax1 = plt.subplot2grid((20,5), (0,0), colspan=1, rowspan=8)
    plt.errorbar(0, m1[m1.set == 'real'].variability.median(),
                 yerr=m1[m1.set == 'real'].variability.mad(),
                 fmt='o', ms=7,
                 color=sns.xkcd_rgb['yellow orange'],
                 mec='k', mew=1,
                 label='Observed')
    sns.stripplot(data=m1[m1['set'] == 'random'].groupby('round').median()['variability'],
                  jitter=0.4,
                  color=sns.xkcd_rgb['grey'],
                  alpha=0.33,
                  label='Permutations',
                  zorder=0)

    plt.legend(loc=(0.1, 0.8), frameon=True)

    plt.ylabel('log$_2$(Nonsynonymous ratio)')
    plt.ylim(-2.5, 2.5)
    plt.xticks([])
    plt.axhline(0,
                color='r',
                linestyle='dashed')
    sns.despine(bottom=True, ax=ax1)

    ax2 = plt.subplot2grid((20,6), (0,2), colspan=4, rowspan=8)
    data = m3[np.isnan(m3['round'])]

    plt.plot((data.start+data.stop)/2.,
             data.variability,
             'o', ms=7,
             color=sns.xkcd_rgb['deep orange'],
             mec='k', mew=1,
             label='Observed')

    tmp = plt.plot((m3.dropna().start+m3.dropna().stop)/2.,
             m3.dropna().variability,
             '.',
             color=sns.xkcd_rgb['grey'],
             alpha=0.33,
             label='Permutations',
             zorder=0)
    for t in tmp:
        t.set_rasterized(True)

    handles, labels = ax2.get_legend_handles_labels()
    objs =[[(x, y)
            for x,y in zip(handles, labels)
            if y == 'Permutations'][0],
           [(x, y)
            for x,y in zip(handles, labels)
            if y == 'Observed'][0]]
    plt.legend([x[0] for x in objs],
               [x[1] for x in objs],
               loc=(0.05, 0.8),
               frameon=True)

    plt.ylim(-2.5, 2.5)
    plt.axhline(0,
                color='r',
                linestyle='dashed')
    plt.ylabel('log$_2$(Nonsynonymous ratio)')
    plt.xlabel('Solvent accessible surface area (A$^2$)')
    sns.despine(ax=ax2)

    ax3 = plt.subplot2grid((20, 7), (12, 0), rowspan=8, colspan=3)

    sns.boxplot(data=m2,
                x='set',
                y='score',
                hue='round',
                palette=[sns.xkcd_rgb['yellow orange'],
                         sns.xkcd_rgb['light grey']],
                notch=True)
    plt.axhline(-np.log10(0.05 + options.sift_offset),
                color='r',
                linestyle='dashed',
                label='Predicted deleterious threshold')
    plt.legend(loc=(0.1, 1),
               frameon=True)
    plt.ylim(0, 10)
    plt.ylabel('-log$_{10}$(SIFT p-value)')
    plt.xlabel('')
    plt.xticks(range(2),
               ['Features', 'Others'])
    sns.despine(bottom=True, ax=ax3)

    ax4 = plt.subplot2grid((20, 7), (12, 4), rowspan=8, colspan=3)

    sns.boxplot(data=m4,
                x='set',
                y='score',
                hue='round',
                palette=[sns.xkcd_rgb['deep orange'],
                         sns.xkcd_rgb['light grey']])
    plt.axhline(2,
                color='r',
                linestyle='dashed',
                label='Predicted deleterious threshold')
    plt.legend(loc=(0.1, 1),
               frameon=True)
    plt.ylabel('FoldX $\Delta\Delta$G')
    plt.xlabel('')
    plt.xticks(range(2),
               ['Buried', 'Exposed'])
    plt.ylim(-6, 12)
    sns.despine(bottom=True, ax=ax4)

    plt.savefig(options.outfile, dpi=options.dpi)
