#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'


def get_options():
    import argparse

    # create the top-level parser
    description = "Create figure 4"
    parser = argparse.ArgumentParser(description=description,
                                     prog='run_figure_4')
    parser.add_argument('scheme', action='store',
                        help='scheme')
    parser.add_argument('overall')
    parser.add_argument('conditions')
    parser.add_argument('categories')
    parser.add_argument('associations')
    parser.add_argument('example1')
    parser.add_argument('example2')
    parser.add_argument('example')
    parser.add_argument('outfile',
                        help='output (including extension)')

    parser.add_argument('--version', action='version',
                        version='%(prog)s '+__version__)

    return parser.parse_args()




if __name__ == "__main__":
    options = get_options()
    import svgutils.transform as sg

    #create new SVG figure
    fig = sg.SVGFigure("10.75in", "10in")

    # load matpotlib-generated figures
    fig1 = sg.fromfile(options.scheme)
    fig2 = sg.fromfile(options.overall)
    fig3 = sg.fromfile(options.conditions)
    fig4 = sg.fromfile(options.categories)
    fig5 = sg.fromfile(options.associations)
    fig6 = sg.fromfile(options.example1)
    fig7 = sg.fromfile(options.example2)
    # fig8 = sg.fromfile('../plots/example_1a.svg')
    # fig9 = sg.fromfile('../plots/example_2a.svg')
    fig10 = sg.fromfile(options.example)

    # get the plot objects
    plot1 = fig1.getroot()
    plot1.moveto(25, 25, scale=2.2)
    plot2 = fig2.getroot()
    plot2.moveto(25, 275, scale=1)
    plot3 = fig3.getroot()
    plot3.moveto(340, 275, scale=1)
    plot4 = fig4.getroot()
    plot4.moveto(700, 250, scale=1)
    plot5 = fig5.getroot()
    plot5.moveto(650, 410, scale=1)
    plot6 = fig6.getroot()
    plot6.moveto(75, 575, scale=1)
    plot7 = fig7.getroot()
    plot7.moveto(260, 575, scale=1)
    # plot8 = fig8.getroot()
    # plot8.moveto(535, 370, scale=1)
    # plot9 = fig9.getroot()
    # plot9.moveto(570, 430, scale=1)
    plot10 = fig10.getroot()
    plot10.moveto(650, 590, scale=1)

    # add text labels
    # txt1 = sg.TextElement(25,  25, "A)", size=12, weight="bold")
    # txt2 = sg.TextElement(560, 25, "B)", size=12, weight="bold")
    # txt3 = sg.TextElement(25, 250, "C)", size=12, weight="bold")
    # txt4 = sg.TextElement(25, 470, "D)", size=12, weight="bold")
    # txt5 = sg.TextElement(560, 430, "E)", size=12, weight="bold")
    # txt6 = sg.TextElement(560, 590, "F)", size=12, weight="bold")
    # txt7 = sg.TextElement(560, 735, "G)", size=12, weight="bold")

    # append plots and labels to figure
    fig.append([plot2,
                plot3,
                plot4,
                plot5,
                plot1,
                plot6,
                plot7,
    #             plot8,
    #             plot9,
    #             plot11,
                plot10,
               ])
    # fig.append([txt1,
    #             txt2,
    #             txt3,
    #             txt4,
    #             txt5,
    #             txt6,
    #             txt7,
    #            ])

    fig.save(options.outfile)
