#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'

def get_options():
    import argparse
    import sys

    # create the top-level parser
    description = "Remove uncommonly present genes"
    parser = argparse.ArgumentParser(description = description,
                                     prog = 'uncommon_genes')

    parser.add_argument('orthdir', action='store',
                        help='Orthologs directory')

    parser.add_argument('--proportion', action='store',
                        type=float,
                        default=0.2,
                        help='Strains proportion cutoff [Default: 0.2]')
    parser.add_argument('--exclude', action='store',
                        default=None,
                        help='Strains to be excluded [Default: consider all]')
    
    parser.add_argument('--version', action='version',
                         version='%(prog)s '+__version__)

    return parser.parse_args()

def parse_orthologs(infile, conversion=None):
    if conversion is None:
        conversion = {}
    d = {}
    for l in open(infile):
        if l.strip().startswith('#'):
            continue
        orth, prot, org = l.strip().split()
        d[orth] = d.get(orth, set())
        d[orth].add( (conversion.get(prot, prot), org) )
    return d

if __name__ == "__main__":
    import os

    options = get_options()

    # Strains to be excluded
    exclude = set()
    try:
        for l in open(options.exclude):
            exclude.add( l.rstrip().split('_')[0] )
    except:
        pass

    d = {}
    files = [x for x in os.listdir(options.orthdir)
             if x.endswith('.pangenome.tsv')]
    for f in files:
        gid = os.path.split(f)[-1].split('_')[0]
        if gid in exclude:
            continue
        d[gid] = d.get(gid, [])
        d[gid].append(f)
    for k in d:
        d[k] = sorted(d[k])[0]

    freq = {}
    for k, infile in d.items():
        orth = parse_orthologs(os.path.join(options.orthdir, infile))
        for group, genes in orth.items():
            if 'target' not in {x[1] for x in genes}:
                for gene in {x[0] for x in genes}:
                    freq[gene] = freq.get(gene, 0)
                    freq[gene] += 1
    for k in freq:
        freq[k] = freq[k]/float(len(d))

    for k, v in freq.items():
        if v >= options.proportion:
            print(k)
